# Generated by Django 2.2.2 on 2019-07-29 13:00

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nattest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[150, 200], upload_to='photo/')),
                ('document', models.FileField(upload_to='document/')),
                ('bankvoucher', models.FileField(upload_to='bankvoucher/')),
                ('testdate', models.DateField(max_length=30)),
                ('grade', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('testplace', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('role', models.IntegerField(default=0)),
            ],
        ),
    ]
