# Generated by Django 2.2.2 on 2019-07-29 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nattest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nattest',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
