# Generated by Django 2.2.2 on 2019-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nattest', '0002_nattest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nattest',
            name='id',
            field=models.AutoField(default='NAT0000', primary_key=True, serialize=False, unique=True),
        ),
    ]
